server:
  port: 8096
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skills
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

